title: Some-Blog
description: "A Jekyll Blog Theme For Somebody"
author:
  name: "Somebody"
  email: "somebody@somewebsite.somedomain"
  url: "https://this.domain"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "SomeOwner"
year : "2020"
